GET localhost:8080/residents/4/relationship
Content-Type: application/json

###

POST localhost:8080/residents/4/relationship
Content-Type: application/json

{
  "familySerialNumber": 8,
  "relationship": "자녀"
}

###

PUT localhost:8080/residents/4/relationship/8
Content-Type: application/json

{
  "relationship": "강아지"
}

###

DELETE localhost:8080/residents/4/relationship/8